name: Feature Request
description: "Submit a proposal for a new feature"
title: "Feature: "
labels: [feature]
body:
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "Feature description"
      description: "What should be added?"
      placeholder: "You should add ..."
