name: PR Docker Build

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  build-pr:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract PR number
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "Building for PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/kmendell/svelocker-ui
          tags: |
            type=raw,value=pr-${{ env.PR_NUMBER }}
            type=raw,value=pr-${{ env.PR_NUMBER }}-${{ github.run_number }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.title=SveLocker UI - PR #${{ env.PR_NUMBER }}
            org.opencontainers.image.description=PR Build for ${{ github.event.pull_request.title }}
            org.opencontainers.image.source=${{ github.event.pull_request.html_url }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const imageUrl = `ghcr.io/kmendell/svelocker-ui:pr-${prNumber}`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🐳 Docker image built and pushed!\n\n` +
                    `**Image:** \`${imageUrl}\`\n\n` +
                    `You can pull and run this image with:\n` +
                    '```bash\n' +
                    `docker pull ${imageUrl}\n` +
                    `docker run -p 3000:3000 ${imageUrl}\n` +
                    '```'
            });
